### ISSUE TITLE
Crash on OpenBSD

### ISSUE THREAD

**Issue by siccegge** [grosjo/fts-xapian#181]
Hej!

FTS-Xapian is crashing here for a while now on OpenBSD

```
(gdb) bt
#0  _libc_feof (fp=0x0) at /usr/src/lib/libc/stdio/feof.c:48
#1  0x00000e603f4c066f in _ZL34fts_backend_xapian_get_free_memoryv () from /usr/local/lib/dovecot/lib21_fts_xapian_plugin.so
#2  0x00000e603f4be621 in _ZL39fts_backend_xapian_update_set_build_keyP26fts_backend_update_contextPK21fts_backend_build_key () from /usr/local/lib/dovecot/lib21_fts_xapian_plugin.so
#3  0x00000e60b2949463 in fts_backend_update_set_build_key () from /usr/local/lib/dovecot/lib20_fts_plugin.so
#4  0x00000e60b294a885 in fts_build_mail () from /usr/local/lib/dovecot/lib20_fts_plugin.so
#5  0x00000e60b29516ae in fts_mail_precache () from /usr/local/lib/dovecot/lib20_fts_plugin.so
#6  0x00000e60070a95d4 in mail_precache () from /usr/local/lib/dovecot/libdovecot-storage.so.4.1
#7  0x00000e5dfcec9ebd in cmd_index_run () from /usr/local/bin/doveadm
#8  0x00000e5dfcec4393 in doveadm_mail_next_user () from /usr/local/bin/doveadm
#9  0x00000e5dfcec53d0 in doveadm_cmd_ver2_to_mail_cmd_wrapper () from /usr/local/bin/doveadm
#10 0x00000e5dfced7b38 in doveadm_cmd_run_ver2 () from /usr/local/bin/doveadm
#11 0x00000e5dfced74ce in doveadm_cmd_try_run_ver2 () from /usr/local/bin/doveadm
#12 0x00000e5dfcedb262 in main () from /usr/local/bin/doveadm
```

blindly guessing -- maybe OpenBSD should go to the Free/NetBSD codepath there and not the linux one?

**Comment by grosjo** [comment]
Can you test with latest git ?

**Comment by grosjo** [comment]
@siccegge any feedback on the version you use ?

**Comment by grosjo** [comment]
Do not hesitate to re-open if the crash happens on a recent version
